spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/ZFrecruit
    username: postgres
    password: polska525
    initialization-mode: always
server:
  port: 8080
  error:
    include-binding-errors: always
logging:
  file:
    path: /
    name: logs.txt
  level:
    root: WARN
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG